### PR TITLE
Initial support for multiple languages

### LINKED ISSUE #4: Support for languages other than US English
> Hi, we're looking for a library to parse dates. date_time_parser is working pretty well for American dates, but we also have data from European languages (e.g. German, French). An example would be 04 août 2020.

> [A similar library in Python](https://dateparser.readthedocs.io/en/latest/) is able to support languages other than US English, however this library doesn't seem to have such capabilities. Is this something you might consider adding? Or maybe this topic could be open for a potential PR (we might not have time to submit it soon though)? Thanks.

Moved from https://github.com/taxjar/date_time_parser/issues/38

### PR DESCRIPTION
**Pull request by dkuku**
Closes #4
I prepared initial support for multiple languages.
This can be enabled in config by specifying the `languages` key. 
It uses the translations provided by timex but can be switched to anything else.
I tested it with `pl` and I left the tests commented out because it need's to be enabled for the test to work.

### CODE REVIEW

**Comment by dbernheisel** [comment]
Looking good! However I don't want to expand using Timex due to #1. I can help by creating an IANA file parser to provide the timezone abbreviations, and maybe use/borrow ex_cldr for translating months. 

What do you think?

**Comment by dkuku** [comment]
Sure, I just used timex because it was already installed. I have problems
using it in projects due to the max version pinning.

**Comment by dkuku** [comment]
@dbernheisel I'm struggling to find in ex_cldr and the child libraries any functions that returns list of months and weekdays with the abbreviations. I may use some kind of hacks to get the values by formatting some fake date with only weekday or month but it's not the way to go

**Comment by dbernheisel** [comment]
@dkuku  I tried this in Livebook, and it seems to work ok. You might conditionally check if the user has Cldr available, have the user pass in their Cldr backend, and date_time_parser use it to compile available translations. If the user doens't have Cldr in their system, I'm not sure I want to offer translations other than English.

---

# ExCLDR Translation

```elixir
Mix.install([
  {:ex_cldr_dates_times, "~> 2.0"}
])
```

## Config

```elixir
defmodule MyApp.Cldr do
  use Cldr,
    locales: ["en", "fr", "es"],
    default_locale: "en",
    providers: [Cldr.Number, Cldr.Calendar, Cldr.DateTime]
end
```
```elixir
locales = MyApp.Cldr.known_locale_names()

for month <- 1..12 do
  trans =
    Enum.map(locales, fn l ->
      Cldr.DateTime.Formatter.month(Date.new!(2022, month, 1), 4, l, MyApp.Cldr)
    end)

  {month, trans}
end
```



```elixir
[
  {1, ["January", "enero", "janvier"]},
  {2, ["February", "febrero", "février"]},
  {3, ["March", "marzo", "mars"]},
  {4, ["April", "abril", "avril"]},
  {5, ["May", "mayo", "mai"]},
  {6, ["June", "junio", "juin"]},
  {7, ["July", "julio", "juillet"]},
  {8, ["August", "agosto", "août"]},
  {9, ["September", "septiembre", "septembre"]},
  {10, ["October", "octubre", "octobre"]},
  {11, ["November", "noviembre", "novembre"]},
  {12, ["December", "diciembre", "décembre"]}
]
```

**Comment by dkuku** [comment]
Thanks-I was thinking about this but I was not sure about it, it felt a bit
hacky. I'll try to do it tomorrow.

**Comment by dkuku** [comment]
@dbernheisel It's working but I have problems to test it because the code is either compiled in one version or another.
I can switch between the implementations but I don't have any idea how to test it - easiest way would be to have 2 separate ci or refactor the code and have date_time_parser and date_time_parser_cldr packages.

**Comment by dkuku** [comment]
I'm thinking of some optimisation - instead of matching `January` and `Jan` we can try to match to just strings starting with `Jan`. 
Also I'm Polish and the month name can have multiple endings but it always starts the same. In cldr you have `month` and `standalone_month` which for english are the same but for other languages may not.

**Comment by dbernheisel** [comment]
@dkuku Once we have some tests added, let's get this merged! It's looking good.

**Comment by dkuku** [comment]
> @dkuku Once we have some tests added, let's get this merged! It's looking good.

👍🏻  I can look into it during holidays.

**Comment by dkuku** [comment]
I can compile it and run the tests with `mix tests` - note the `s` at the end.
But I had to disable the warnings as errors check in mix.exs

**Comment by dbernheisel** [comment]
I have not forgotten about this :) I'm going to incorporate this in with some of my changes and get this going. I appreciate your work and your patience.

**Comment by dkuku** [comment]
That's why the 'allow edits from maintainers' checkbox is here - looking to see the next release :)

**Comment by dbernheisel** [comment]
Unfortunately there's an issue with this approach. In the combinators.ex.eex, we're using `@month_map` which gets compiled into the real combinators file by Nimble Parsec.

Where this is ok is in a function like `vocal_month_to_numeric_month` since that's called during runtime and the map is copied over into the final file, but the `@months_map` is also used to determine which strings to look for and is inlined by NimbleParsec into functions; this means that whenever a user adds `:date_time_parser` to their app, they'd have to re-compile combinators.ex.eex into combinators.ex in order to benefit from their Cldr.Backend which provides the translations. 

Maybe this is ok, but it would mean that NimbleParsec would have to be a non-dev dependency and will be a 2-phase compilation again.

**Comment by dkuku** [comment]
Yes, you're right. But this would pe only needed if someone want's to
configure the parser for custom language. By default it's not needed and
the dependency would only be needed in dev envs for recompilation.

**Comment by dbernheisel** [comment]
I'm going to close for now, mostly because of length of time open, but also there's an order-of-operations issue with this approach in that it requires cldr languages to be present during the build process of the library, and not the build process of the app using the library. We'll need to re-think the approach.

**Pull request closed without merging**
